name: Generate and Deploy Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci

      - name: Generate Site
        run: npm run generate

      - name: Copy Public Folder to New Branch
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan generated-site
          git rm -rf .
          cp -r .output/public/* .
          git add -A
          git commit -m "Generated site from main branch"
          git push origin generated-site
